//called via root -l LLVisualization.C
//this produces the Lost Lepton prediction vs. MC truth plots.
//so far the numbers are hard coded (due to lack of time to implement a proper code to read the prediction tables
//so a large overhaul of this macro is needed
//note that these hardcoded numbers are also used later for final result tables and plots !!!
//NOTE: --> in LostLeptonEstimate (and also TauEstimation.C) there is a new function which produces some of these histograms
//          look for PredictionFile(...) - use these to read in the numbers you need instead of using the hardcoded stuff.
void LLVisualization(){
    
    gROOT->SetStyle("Plain");
	gStyle->SetPalette(1);
	gStyle->SetOptStat(0);
    
    //visuzalization plots as
    //electron/muon/tau - low/medium/high HT (each histogram contains the nine topological regions)
    //data prediction
    TH1D *lHT_ele = new TH1D("lHT_ele","",9,0,9); lHT_ele->SetMarkerStyle(20), lHT_ele->SetMarkerColor(kBlack); lHT_ele->SetLineWidth(3); lHT_ele->SetLineColor(kBlack);
    TH1D *lHT_muo = new TH1D("lHT_muo","",9,0,9); lHT_muo->SetMarkerStyle(20), lHT_muo->SetMarkerColor(kBlack); lHT_muo->SetLineWidth(3); lHT_muo->SetLineColor(kBlack);
    TH1D *lHT_tau = new TH1D("lHT_tau","",9,0,9); lHT_tau->SetMarkerStyle(20), lHT_tau->SetMarkerColor(kBlack); lHT_tau->SetLineWidth(3); lHT_tau->SetLineColor(kBlack);
    TH1D *mHT_ele = new TH1D("mHT_ele","",9,0,9); mHT_ele->SetMarkerStyle(20), mHT_ele->SetMarkerColor(kBlack); mHT_ele->SetLineWidth(3); mHT_ele->SetLineColor(kBlack);
    TH1D *mHT_muo = new TH1D("mHT_muo","",9,0,9); mHT_muo->SetMarkerStyle(20), mHT_muo->SetMarkerColor(kBlack); mHT_muo->SetLineWidth(3); mHT_muo->SetLineColor(kBlack);
    TH1D *mHT_tau = new TH1D("mHT_tau","",9,0,9); mHT_tau->SetMarkerStyle(20), mHT_tau->SetMarkerColor(kBlack); mHT_tau->SetLineWidth(3); mHT_tau->SetLineColor(kBlack);
    TH1D *hHT_ele = new TH1D("hHT_ele","",9,0,9); hHT_ele->SetMarkerStyle(20), hHT_ele->SetMarkerColor(kBlack); hHT_ele->SetLineWidth(3); hHT_ele->SetLineColor(kBlack);
    TH1D *hHT_muo = new TH1D("hHT_muo","",9,0,9); hHT_muo->SetMarkerStyle(20), hHT_muo->SetMarkerColor(kBlack); hHT_muo->SetLineWidth(3); hHT_muo->SetLineColor(kBlack);
    TH1D *hHT_tau = new TH1D("hHT_tau","",9,0,9); hHT_tau->SetMarkerStyle(20), hHT_tau->SetMarkerColor(kBlack); hHT_tau->SetLineWidth(3); hHT_tau->SetLineColor(kBlack);
    //mc truth
    TH1D *lHT_eleMC = new TH1D("lHT_eleMC","",9,0,9); lHT_eleMC->SetFillStyle(3001); lHT_eleMC->SetFillColor(kBlue);
    TH1D *lHT_muoMC = new TH1D("lHT_muoMC","",9,0,9); lHT_muoMC->SetFillStyle(3001); lHT_muoMC->SetFillColor(kBlue);
    TH1D *lHT_tauMC = new TH1D("lHT_tauMC","",9,0,9); lHT_tauMC->SetFillStyle(3001); lHT_tauMC->SetFillColor(kBlue);
    TH1D *mHT_eleMC = new TH1D("mHT_eleMC","",9,0,9); mHT_eleMC->SetFillStyle(3001); mHT_eleMC->SetFillColor(kBlue);
    TH1D *mHT_muoMC = new TH1D("mHT_muoMC","",9,0,9); mHT_muoMC->SetFillStyle(3001); mHT_muoMC->SetFillColor(kBlue);
    TH1D *mHT_tauMC = new TH1D("mHT_tauMC","",9,0,9); mHT_tauMC->SetFillStyle(3001); mHT_tauMC->SetFillColor(kBlue);
    TH1D *hHT_eleMC = new TH1D("hHT_eleMC","",9,0,9); hHT_eleMC->SetFillStyle(3001); hHT_eleMC->SetFillColor(kBlue);
    TH1D *hHT_muoMC = new TH1D("hHT_muoMC","",9,0,9); hHT_muoMC->SetFillStyle(3001); hHT_muoMC->SetFillColor(kBlue);
    TH1D *hHT_tauMC = new TH1D("hHT_tauMC","",9,0,9); hHT_tauMC->SetFillStyle(3001); hHT_tauMC->SetFillColor(kBlue);
    
    //visuzalization plots as
    //topological region (each histogram contains the three lepton flavours x the three HT regions)
    //data prediction
    TH1D *j2b0 = new TH1D("j2b0","",9,0,9); j2b0->SetMarkerStyle(20), j2b0->SetMarkerColor(kBlack); j2b0->SetLineWidth(3); j2b0->SetLineColor(kBlack);
    TH1D *j2b1 = new TH1D("j2b1","",9,0,9); j2b1->SetMarkerStyle(20), j2b1->SetMarkerColor(kBlack); j2b1->SetLineWidth(3); j2b1->SetLineColor(kBlack);
    TH1D *j3b0 = new TH1D("j3b0","",9,0,9); j3b0->SetMarkerStyle(20), j3b0->SetMarkerColor(kBlack); j3b0->SetLineWidth(3); j3b0->SetLineColor(kBlack);
    TH1D *j3b1 = new TH1D("j3b1","",9,0,9); j3b1->SetMarkerStyle(20), j3b1->SetMarkerColor(kBlack); j3b1->SetLineWidth(3); j3b1->SetLineColor(kBlack);
    TH1D *j3b2 = new TH1D("j3b2","",9,0,9); j3b2->SetMarkerStyle(20), j3b2->SetMarkerColor(kBlack); j3b2->SetLineWidth(3); j3b2->SetLineColor(kBlack);
    TH1D *j6b0 = new TH1D("j6b0","",9,0,9); j6b0->SetMarkerStyle(20), j6b0->SetMarkerColor(kBlack); j6b0->SetLineWidth(3); j6b0->SetLineColor(kBlack);
    TH1D *j6b1 = new TH1D("j6b1","",9,0,9); j6b1->SetMarkerStyle(20), j6b1->SetMarkerColor(kBlack); j6b1->SetLineWidth(3); j6b1->SetLineColor(kBlack);
    TH1D *j6b2 = new TH1D("j6b2","",9,0,9); j6b2->SetMarkerStyle(20), j6b2->SetMarkerColor(kBlack); j6b2->SetLineWidth(3); j6b2->SetLineColor(kBlack);
    TH1D *j3b3 = new TH1D("j3b3","",9,0,9); j3b3->SetMarkerStyle(20), j3b3->SetMarkerColor(kBlack); j3b3->SetLineWidth(3); j3b3->SetLineColor(kBlack);
    //MC truth
    TH1D *j2b0MC = new TH1D("j2b0MC","",9,0,9); j2b0MC->SetFillStyle(3001); j2b0MC->SetFillColor(kBlue);
    TH1D *j2b1MC = new TH1D("j2b1MC","",9,0,9); j2b1MC->SetFillStyle(3001); j2b1MC->SetFillColor(kBlue);
    TH1D *j3b0MC = new TH1D("j3b0MC","",9,0,9); j3b0MC->SetFillStyle(3001); j3b0MC->SetFillColor(kBlue);
    TH1D *j3b1MC = new TH1D("j3b1MC","",9,0,9); j3b1MC->SetFillStyle(3001); j3b1MC->SetFillColor(kBlue);
    TH1D *j3b2MC = new TH1D("j3b2MC","",9,0,9); j3b2MC->SetFillStyle(3001); j3b2MC->SetFillColor(kBlue);
    TH1D *j6b0MC = new TH1D("j6b0MC","",9,0,9); j6b0MC->SetFillStyle(3001); j6b0MC->SetFillColor(kBlue);
    TH1D *j6b1MC = new TH1D("j6b1MC","",9,0,9); j6b1MC->SetFillStyle(3001); j6b1MC->SetFillColor(kBlue);
    TH1D *j6b2MC = new TH1D("j6b2MC","",9,0,9); j6b2MC->SetFillStyle(3001); j6b2MC->SetFillColor(kBlue);
    TH1D *j3b3MC = new TH1D("j3b3MC","",9,0,9); j3b3MC->SetFillStyle(3001); j3b3MC->SetFillColor(kBlue);

    TLegend *leg = new TLegend(0.61,0.74,0.81,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.04181185);
    leg->SetTextFont(42);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
    leg->AddEntry(j2b0MC, "simulation truth", "f");
    leg->AddEntry(j2b0, "data prediction", "lp");
    
    TH1D *haxis = new TH1D("haxis","",9,0,9);
    haxis->GetXaxis()->SetBinLabel(1, "e,lHT");
    haxis->GetXaxis()->SetBinLabel(2, "#mu,lHT");
    haxis->GetXaxis()->SetBinLabel(3, "#tau,lHT");
    haxis->GetXaxis()->SetBinLabel(4, "e,mHT");
    haxis->GetXaxis()->SetBinLabel(5, "#mu,mHT");
    haxis->GetXaxis()->SetBinLabel(6, "#tau,mHT");
    haxis->GetXaxis()->SetBinLabel(7, "e,hHT");
    haxis->GetXaxis()->SetBinLabel(8, "#mu,hHT");
    haxis->GetXaxis()->SetBinLabel(9, "#tau,hHT");  
   haxis->GetXaxis()->SetTitle("signal region");
   haxis->GetXaxis()->SetLabelFont(42);
   haxis->GetXaxis()->SetLabelOffset(0.007);
   haxis->GetXaxis()->SetLabelSize(0.05);
   haxis->GetXaxis()->SetTitleSize(0.06);
   haxis->GetXaxis()->SetTitleOffset(0.9);
   haxis->GetXaxis()->SetTitleFont(42);
   haxis->GetYaxis()->SetTitle("lost lepton yield");
   haxis->GetYaxis()->SetLabelFont(42);
   haxis->GetYaxis()->SetLabelOffset(0.007);
   haxis->GetYaxis()->SetLabelSize(0.05);
   haxis->GetYaxis()->SetTitleSize(0.06);
   haxis->GetYaxis()->SetTitleOffset(1.25);
   haxis->GetYaxis()->SetTitleFont(42);
   haxis->GetZaxis()->SetLabelFont(42);
   haxis->GetZaxis()->SetLabelOffset(0.007);
   haxis->GetZaxis()->SetLabelSize(0.05);
   haxis->GetZaxis()->SetTitleSize(0.06);
   haxis->GetZaxis()->SetTitleFont(42);
    TH1D *haxis2 = new TH1D("haxis2","",9,0,9);
    haxis2->GetXaxis()->SetBinLabel(1, "2j,0b");
    haxis2->GetXaxis()->SetBinLabel(2, "2j,#geq1b");
    haxis2->GetXaxis()->SetBinLabel(3, "3-5j,0b");
    haxis2->GetXaxis()->SetBinLabel(4, "3-5j,1b");
    haxis2->GetXaxis()->SetBinLabel(5, "3-5j,2b");
    haxis2->GetXaxis()->SetBinLabel(6, "#geq6j,0b");
    haxis2->GetXaxis()->SetBinLabel(7, "#geq6j,1b");
    haxis2->GetXaxis()->SetBinLabel(8, "#geq6j,2b");
    haxis2->GetXaxis()->SetBinLabel(9, "#geq3j,#geq3b");
   haxis2->GetXaxis()->SetTitle("signal region");
   haxis2->GetXaxis()->SetLabelFont(42);
   haxis2->GetXaxis()->SetLabelOffset(0.007);
   haxis2->GetXaxis()->SetLabelSize(0.05);
   haxis2->GetXaxis()->SetTitleSize(0.06);
   haxis2->GetXaxis()->SetTitleOffset(0.9);
   haxis2->GetXaxis()->SetTitleFont(42);
   haxis2->GetYaxis()->SetTitle("lost lepton yield");
   haxis2->GetYaxis()->SetLabelFont(42);
   haxis2->GetYaxis()->SetLabelOffset(0.007);
   haxis2->GetYaxis()->SetLabelSize(0.05);
   haxis2->GetYaxis()->SetTitleSize(0.06);
   haxis2->GetYaxis()->SetTitleOffset(1.25);
   haxis2->GetYaxis()->SetTitleFont(42);
   haxis2->GetZaxis()->SetLabelFont(42);
   haxis2->GetZaxis()->SetLabelOffset(0.007);
   haxis2->GetZaxis()->SetLabelSize(0.05);
   haxis2->GetZaxis()->SetTitleSize(0.06);
   haxis2->GetZaxis()->SetTitleFont(42);

    //hardcoded results
    // error on pred: stat + syst + ISR + doubleLL
    lHT_ele  ->SetBinContent(1,215.07); lHT_ele  ->SetBinError(1,sqrt(pow(12.46,2)+pow(27.09,2)+pow(4.02,2)+pow(0.1,2)));
    lHT_ele  ->SetBinContent(2, 18.84); lHT_ele  ->SetBinError(2,sqrt(pow( 3.59,2)+pow( 2.99,2)+pow(0.37,2)+pow(0.2,2)));
    lHT_ele  ->SetBinContent(3,399.46); lHT_ele  ->SetBinError(3,sqrt(pow(19.51,2)+pow(43.41,2)+pow(7.28,2)+pow(0.36,2)));
    lHT_ele  ->SetBinContent(4,128.33); lHT_ele  ->SetBinError(4,sqrt(pow(11.26,2)+pow(14.73,2)+pow(2.25,2)+pow(0.56,2)));
    lHT_ele  ->SetBinContent(5, 29.55); lHT_ele  ->SetBinError(5,sqrt(pow( 5.98,2)+pow( 3.74,2)+pow(0.45,2)+pow(0.53,2)));
    lHT_ele  ->SetBinContent(6,  9.70); lHT_ele  ->SetBinError(6,sqrt(pow( 3.50,2)+pow( 1.58,2)+pow(0.01,2)+pow(0.32,2)));
    lHT_ele  ->SetBinContent(7, 15.81); lHT_ele  ->SetBinError(7,sqrt(pow( 4.56,2)+pow( 2.36,2)+pow(0.00,2)+pow(0.43,2)));
    lHT_ele  ->SetBinContent(8,  9.66); lHT_ele  ->SetBinError(8,sqrt(pow( 3.22,2)+pow( 1.75,2)+pow(0.07,2)+pow(0.01,2)));
    lHT_ele  ->SetBinContent(9,  4.79); lHT_ele  ->SetBinError(9,sqrt(pow( 2.14,2)+pow( 1.10,2)+pow(0.02,2)+pow(0.07,2)));
    lHT_eleMC->SetBinContent(1,247.94); lHT_eleMC->SetBinError(1, 4.93);
    lHT_eleMC->SetBinContent(2, 19.37); lHT_eleMC->SetBinError(2, 2.09);
    lHT_eleMC->SetBinContent(3,404.54); lHT_eleMC->SetBinError(3, 9.28);
    lHT_eleMC->SetBinContent(4,113.31); lHT_eleMC->SetBinError(4, 5.93);
    lHT_eleMC->SetBinContent(5, 38.79); lHT_eleMC->SetBinError(5, 2.84);
    lHT_eleMC->SetBinContent(6, 11.04); lHT_eleMC->SetBinError(6, 1.21);
    lHT_eleMC->SetBinContent(7, 14.37); lHT_eleMC->SetBinError(7, 1.29);
    lHT_eleMC->SetBinContent(8,  8.99); lHT_eleMC->SetBinError(8, 0.89);
    lHT_eleMC->SetBinContent(9,  4.66); lHT_eleMC->SetBinError(9, 0.78);
  
    lHT_muo  ->SetBinContent(1,174.00); lHT_muo  ->SetBinError(1,sqrt(pow( 8.55,2)+pow(30.66,2)+pow(4.00,2)+pow(0.60,2)));
    lHT_muo  ->SetBinContent(2, 17.60); lHT_muo  ->SetBinError(2,sqrt(pow( 2.60,2)+pow( 3.72,2)+pow(0.35,2)+pow(0.14,2)));
    lHT_muo  ->SetBinContent(3,351.08); lHT_muo  ->SetBinError(3,sqrt(pow(14.26,2)+pow(50.43,2)+pow(7.40,2)+pow(0.82,2)));
    lHT_muo  ->SetBinContent(4,106.24); lHT_muo  ->SetBinError(4,sqrt(pow( 8.05,2)+pow(20.92,2)+pow(0.26,2)+pow(0.51,2)));
    lHT_muo  ->SetBinContent(5, 28.73); lHT_muo  ->SetBinError(5,sqrt(pow( 4.25,2)+pow( 4.65,2)+pow(0.48,2)+pow(0.59,2)));
    lHT_muo  ->SetBinContent(6,  8.33); lHT_muo  ->SetBinError(6,sqrt(pow( 2.32,2)+pow( 1.51,2)+pow(0.17,2)+pow(0.03,2)));
    lHT_muo  ->SetBinContent(7, 11.24); lHT_muo  ->SetBinError(7,sqrt(pow( 2.81,2)+pow( 1.95,2)+pow(0.03,2)+pow(0.28,2)));
    lHT_muo  ->SetBinContent(8,  1.93); lHT_muo  ->SetBinError(8,sqrt(pow( 1.13,2)+pow( 0.37,2)+pow(0.02,2)+pow(0.18,2)));
    lHT_muo  ->SetBinContent(9,  6.76); lHT_muo  ->SetBinError(9,sqrt(pow( 2.06,2)+pow( 1.57,2)+pow(0.06,2)+pow(0.02,2)));
    lHT_muoMC->SetBinContent(1,203.15); lHT_muoMC->SetBinError(1, 5.25);
    lHT_muoMC->SetBinContent(2, 14.01); lHT_muoMC->SetBinError(2, 1.88);
    lHT_muoMC->SetBinContent(3,340.25); lHT_muoMC->SetBinError(3, 9.84);
    lHT_muoMC->SetBinContent(4,105.22); lHT_muoMC->SetBinError(4,14.10);
    lHT_muoMC->SetBinContent(5, 33.30); lHT_muoMC->SetBinError(5, 3.12);
    lHT_muoMC->SetBinContent(6,  8.99); lHT_muoMC->SetBinError(6, 0.98);
    lHT_muoMC->SetBinContent(7, 11.70); lHT_muoMC->SetBinError(7, 1.28);
    lHT_muoMC->SetBinContent(8,  7.42); lHT_muoMC->SetBinError(8, 0.84);
    lHT_muoMC->SetBinContent(9,  4.02); lHT_muoMC->SetBinError(9, 0.75);

    lHT_tau  ->SetBinContent(1,274.04); lHT_tau  ->SetBinError(1,sqrt(pow(49.46,2)+pow(32.70,2)+pow(4.35,2)+pow(0.22,2)));
    lHT_tau  ->SetBinContent(2, 14.99); lHT_tau  ->SetBinError(2,sqrt(pow(13.74,2)+pow( 4.24,2)+pow(0.09,2)+pow(0.91,2)));
    lHT_tau  ->SetBinContent(3,468.93); lHT_tau  ->SetBinError(3,sqrt(pow(42.55,2)+pow(54.41,2)+pow(7.93,2)+pow(0.24,2)));
    lHT_tau  ->SetBinContent(4,170.09); lHT_tau  ->SetBinError(4,sqrt(pow(27.99,2)+pow(24.89,2)+pow(2.79,2)+pow(0.12,2)));
    lHT_tau  ->SetBinContent(5, 84.82); lHT_tau  ->SetBinError(5,sqrt(pow(29.44,2)+pow(16.38,2)+pow(1.15,2)+pow(1.18,2)));
    lHT_tau  ->SetBinContent(6, 29.44); lHT_tau  ->SetBinError(6,sqrt(pow( 8.12,2)+pow( 5.05,2)+pow(0.02,2)+pow(0.15,2)));
    lHT_tau  ->SetBinContent(7, 18.85); lHT_tau  ->SetBinError(7,sqrt(pow( 6.95,2)+pow( 3.62,2)+pow(0.11,2)+pow(0.11,2)));
    lHT_tau  ->SetBinContent(8,  7.09); lHT_tau  ->SetBinError(8,sqrt(pow( 5.53,2)+pow( 1.40,2)+pow(0.02,2)+pow(0.16,2)));
    lHT_tau  ->SetBinContent(9,  8.12); lHT_tau  ->SetBinError(9,sqrt(pow( 6.59,2)+pow( 2.25,2)+pow(0.23,2)+pow(0.49,2))); 
    lHT_tauMC->SetBinContent(1,262.54); lHT_tauMC->SetBinError(1, 5.22);
    lHT_tauMC->SetBinContent(2, 20.20); lHT_tauMC->SetBinError(2, 2.07);
    lHT_tauMC->SetBinContent(3,452.74); lHT_tauMC->SetBinError(3,10.89);
    lHT_tauMC->SetBinContent(4,157.92); lHT_tauMC->SetBinError(4,16.79);
    lHT_tauMC->SetBinContent(5, 44.68); lHT_tauMC->SetBinError(5, 4.66);
    lHT_tauMC->SetBinContent(6, 15.72); lHT_tauMC->SetBinError(6, 1.42);
    lHT_tauMC->SetBinContent(7, 18.19); lHT_tauMC->SetBinError(7, 1.52);
    lHT_tauMC->SetBinContent(8, 13.98); lHT_tauMC->SetBinError(8, 1.41);
    lHT_tauMC->SetBinContent(9,  7.23); lHT_tauMC->SetBinError(9, 1.16);
    

    mHT_ele  ->SetBinContent(1, 76.94); mHT_ele  ->SetBinError(1,sqrt(pow( 7.14,2)+pow(10.52,2)+pow(3.19,2)+pow(0.20,2)));
    mHT_ele  ->SetBinContent(2,  5.94); mHT_ele  ->SetBinError(2,sqrt(pow( 2.00,2)+pow( 1.04,2)+pow(0.33,2)+pow(0.19,2)));
    mHT_ele  ->SetBinContent(3,126.84); mHT_ele  ->SetBinError(3,sqrt(pow(10.27,2)+pow(15.07,2)+pow(3.26,2)+pow(0.12,2)));
    mHT_ele  ->SetBinContent(4, 46.06); mHT_ele  ->SetBinError(4,sqrt(pow( 5.86,2)+pow( 8.85,2)+pow(0.80,2)+pow(1.54,2)));
    mHT_ele  ->SetBinContent(5, 19.15); mHT_ele  ->SetBinError(5,sqrt(pow( 4.33,2)+pow( 2.70,2)+pow(0.38,2)+pow(0.44,2)));
    mHT_ele  ->SetBinContent(6,  8.60); mHT_ele  ->SetBinError(6,sqrt(pow( 3.25,2)+pow( 1.33,2)+pow(0.08,2)+pow(0.20,2)));
    mHT_ele  ->SetBinContent(7, 19.44); mHT_ele  ->SetBinError(7,sqrt(pow( 4.95,2)+pow( 2.82,2)+pow(0.12,2)+pow(0.16,2)));
    mHT_ele  ->SetBinContent(8, 21.57); mHT_ele  ->SetBinError(8,sqrt(pow( 5.59,2)+pow( 2.74,2)+pow(0.10,2)+pow(0.62,2)));
    mHT_ele  ->SetBinContent(9,  3.02); mHT_ele  ->SetBinError(9,sqrt(pow( 1.78,2)+pow( 0.58,2)+pow(0.01,2)+pow(0.49,2)));  
    mHT_eleMC->SetBinContent(1,106.35); mHT_eleMC->SetBinError(1, 3.19);
    mHT_eleMC->SetBinContent(2, 13.02); mHT_eleMC->SetBinError(2, 1.35);
    mHT_eleMC->SetBinContent(3,164.25); mHT_eleMC->SetBinError(3, 4.76);
    mHT_eleMC->SetBinContent(4, 56.24); mHT_eleMC->SetBinError(4, 3.73);
    mHT_eleMC->SetBinContent(5, 28.95); mHT_eleMC->SetBinError(5, 2.53);
    mHT_eleMC->SetBinContent(6, 15.03); mHT_eleMC->SetBinError(6, 1.42);
    mHT_eleMC->SetBinContent(7, 21.58); mHT_eleMC->SetBinError(7, 1.71);
    mHT_eleMC->SetBinContent(8, 26.12); mHT_eleMC->SetBinError(8, 2.34);
    mHT_eleMC->SetBinContent(9,  8.19); mHT_eleMC->SetBinError(9, 1.41);
 
    mHT_muo  ->SetBinContent(1, 78.12); mHT_muo  ->SetBinError(1,sqrt(pow( 5.92,2)+pow(13.82,2)+pow(3.23,2)+pow(0.03,2)));
    mHT_muo  ->SetBinContent(2, 13.99); mHT_muo  ->SetBinError(2,sqrt(pow( 2.62,2)+pow( 2.80,2)+pow(0.83,2)+pow(0.05,2)));
    mHT_muo  ->SetBinContent(3,122.86); mHT_muo  ->SetBinError(3,sqrt(pow( 8.12,2)+pow(19.05,2)+pow(3.51,2)+pow(0.44,2)));
    mHT_muo  ->SetBinContent(4, 56.04); mHT_muo  ->SetBinError(4,sqrt(pow( 5.70,2)+pow( 8.79,2)+pow(0.16,2)+pow(0.68,2)));
    mHT_muo  ->SetBinContent(5, 20.46); mHT_muo  ->SetBinError(5,sqrt(pow( 3.46,2)+pow( 3.43,2)+pow(0.24,2)+pow(1.19,2)));
    mHT_muo  ->SetBinContent(6, 11.21); mHT_muo  ->SetBinError(6,sqrt(pow( 2.82,2)+pow( 1.91,2)+pow(0.26,2)+pow(0.20,2)));
    mHT_muo  ->SetBinContent(7, 21.37); mHT_muo  ->SetBinError(7,sqrt(pow( 4.00,2)+pow( 3.33,2)+pow(0.21,2)+pow(0.14,2)));
    mHT_muo  ->SetBinContent(8, 14.96); mHT_muo  ->SetBinError(8,sqrt(pow( 3.12,2)+pow( 2.41,2)+pow(0.00,2)+pow(0.05,2)));
    mHT_muo  ->SetBinContent(9, 11.17); mHT_muo  ->SetBinError(9,sqrt(pow( 2.89,2)+pow( 2.25,2)+pow(0.06,2)+pow(0.01,2)));   
    mHT_muoMC->SetBinContent(1, 96.83); mHT_muoMC->SetBinError(1, 2.89);
    mHT_muoMC->SetBinContent(2, 12.83); mHT_muoMC->SetBinError(2, 1.58);
    mHT_muoMC->SetBinContent(3,137.49); mHT_muoMC->SetBinError(3, 4.37);
    mHT_muoMC->SetBinContent(4, 50.56); mHT_muoMC->SetBinError(4, 5.13);
    mHT_muoMC->SetBinContent(5, 24.55); mHT_muoMC->SetBinError(5, 4.39);
    mHT_muoMC->SetBinContent(6, 12.27); mHT_muoMC->SetBinError(6, 1.33);
    mHT_muoMC->SetBinContent(7, 17.53); mHT_muoMC->SetBinError(7, 1.34);
    mHT_muoMC->SetBinContent(8, 16.71); mHT_muoMC->SetBinError(8, 1.60);
    mHT_muoMC->SetBinContent(9,  7.82); mHT_muoMC->SetBinError(9, 1.24);

    mHT_tau  ->SetBinContent(1,121.86); mHT_tau  ->SetBinError(1,sqrt(pow(33.40,2)+pow(15.75,2)+pow(2.21,2)+pow(0.04,2)));
    //mHT_tau  ->SetBinContent(2,); mHT_tau  ->SetBinError(2,sqrt(pow( ,2)+pow(,2)+pow(,2)+pow(,2)));
    mHT_tau  ->SetBinContent(3,155.19); mHT_tau  ->SetBinError(3,sqrt(pow(23.89,2)+pow(18.69,2)+pow(3.71,2)+pow(0.37,2)));
    mHT_tau  ->SetBinContent(4, 78.34); mHT_tau  ->SetBinError(4,sqrt(pow(20.67,2)+pow(11.16,2)+pow(0.37,2)+pow(0.73,2)));
    mHT_tau  ->SetBinContent(5, 28.22); mHT_tau  ->SetBinError(5,sqrt(pow(12.58,2)+pow( 5.16,2)+pow(0.64,2)+pow(0.71,2)));
    mHT_tau  ->SetBinContent(6, 26.23); mHT_tau  ->SetBinError(6,sqrt(pow( 7.60,2)+pow( 4.09,2)+pow(0.41,2)+pow(0.15,2)));
    mHT_tau  ->SetBinContent(7, 18.06); mHT_tau  ->SetBinError(7,sqrt(pow( 7.16,2)+pow( 2.95,2)+pow(0.23,2)+pow(0.23,2)));
    mHT_tau  ->SetBinContent(8, 27.39); mHT_tau  ->SetBinError(8,sqrt(pow(10.16,2)+pow( 4.24,2)+pow(0.26,2)+pow(0.48,2)));
    mHT_tau  ->SetBinContent(9, 36.27); mHT_tau  ->SetBinError(9,sqrt(pow(17.27,2)+pow( 9.11,2)+pow(0.54,2)+pow(0.41,2))); 
    mHT_tauMC->SetBinContent(1,107.15); mHT_tauMC->SetBinError(1, 3.05);
    mHT_tauMC->SetBinContent(2, 15.22); mHT_tauMC->SetBinError(2, 1.71);
    mHT_tauMC->SetBinContent(3,180.91); mHT_tauMC->SetBinError(3, 5.49);
    mHT_tauMC->SetBinContent(4, 72.15); mHT_tauMC->SetBinError(4, 6.12);
    mHT_tauMC->SetBinContent(5, 33.24); mHT_tauMC->SetBinError(5, 4.17);
    mHT_tauMC->SetBinContent(6, 19.87); mHT_tauMC->SetBinError(6, 1.72);
    mHT_tauMC->SetBinContent(7, 32.69); mHT_tauMC->SetBinError(7, 2.57);
    mHT_tauMC->SetBinContent(8, 32.17); mHT_tauMC->SetBinError(8, 2.56);
    mHT_tauMC->SetBinContent(9, 12.50); mHT_tauMC->SetBinError(9, 1.93);


    hHT_ele  ->SetBinContent(1, 12.08); hHT_ele  ->SetBinError(1,sqrt(pow( 2.81,2)+pow( 2.07,2)+pow(0.46,2)+pow(0.06,2)));
    hHT_ele  ->SetBinContent(2,  0.74); hHT_ele  ->SetBinError(2,sqrt(pow( 0.78,2)+pow( 0.24,2)+pow(0.07,2)+pow(0.03,2)));
    hHT_ele  ->SetBinContent(3, 16.34); hHT_ele  ->SetBinError(3,sqrt(pow( 3.54,2)+pow( 2.42,2)+pow(0.33,2)+pow(0.06,2)));
    hHT_ele  ->SetBinContent(4,  2.58); hHT_ele  ->SetBinError(4,sqrt(pow( 1.30,2)+pow( 0.58,2)+pow(0.07,2)+pow(0.12,2)));
    hHT_ele  ->SetBinContent(5,  4.08); hHT_ele  ->SetBinError(5,sqrt(pow( 2.35,2)+pow( 1.31,2)+pow(0.06,2)+pow(0.14,2)));
    hHT_ele  ->SetBinContent(6,  2.88); hHT_ele  ->SetBinError(6,sqrt(pow( 2.88,2)+pow( 0.86,2)+pow(0.14,2)+pow(0.25,2)));
    hHT_ele  ->SetBinContent(7,  2.97); hHT_ele  ->SetBinError(7,sqrt(pow( 2.10,2)+pow( 0.70,2)+pow(0.07,2)+pow(0.05,2)));
    hHT_ele  ->SetBinContent(8,  3.85); hHT_ele  ->SetBinError(8,sqrt(pow( 2.23,2)+pow( 1.01,2)+pow(0.00,2)+pow(0.17,2)));
//    hHT_ele  ->SetBinContent(9,); hHT_ele  ->SetBinError(9,sqrt(pow( ,2)+pow( ,2)+pow(,2)+pow(,2)));
    hHT_eleMC->SetBinContent(1, 13.82); hHT_eleMC->SetBinError(1, 1.06);
    hHT_eleMC->SetBinContent(2,  2.42); hHT_eleMC->SetBinError(2, 0.49);
    hHT_eleMC->SetBinContent(3, 21.06); hHT_eleMC->SetBinError(3, 1.37);
    hHT_eleMC->SetBinContent(4,  5.33); hHT_eleMC->SetBinError(4, 0.68);
    hHT_eleMC->SetBinContent(5,  3.37); hHT_eleMC->SetBinError(5, 0.65);
    hHT_eleMC->SetBinContent(6,  5.04); hHT_eleMC->SetBinError(6, 1.02);
    hHT_eleMC->SetBinContent(7,  4.39); hHT_eleMC->SetBinError(7, 0.64);
    hHT_eleMC->SetBinContent(8,  3.07); hHT_eleMC->SetBinError(8, 0.54);
    hHT_eleMC->SetBinContent(9,  0.83); hHT_eleMC->SetBinError(9, 0.28);

    hHT_muo  ->SetBinContent(1,  7.16); hHT_muo  ->SetBinError(1,sqrt(pow( 1.74,2)+pow( 1.46,2)+pow(0.33,2)+pow(0.08,2)));
    hHT_muo  ->SetBinContent(2,  2.20); hHT_muo  ->SetBinError(2,sqrt(pow( 1.10,2)+pow( 0.71,2)+pow(0.08,2)+pow(0.06,2)));
    hHT_muo  ->SetBinContent(3, 18.36); hHT_muo  ->SetBinError(3,sqrt(pow( 2.99,2)+pow( 3.30,2)+pow(0.42,2)+pow(0.05,2)));
    hHT_muo  ->SetBinContent(4,  7.97); hHT_muo  ->SetBinError(4,sqrt(pow( 2.22,2)+pow( 1.69,2)+pow(0.07,2)+pow(0.41,2)));
    hHT_muo  ->SetBinContent(5,  0.47); hHT_muo  ->SetBinError(5,sqrt(pow( 0.47,2)+pow( 0.17,2)+pow(0.00,2)+pow(0.27,2)));
    hHT_muo  ->SetBinContent(6,  1.95); hHT_muo  ->SetBinError(6,sqrt(pow( 1.41,2)+pow( 0.56,2)+pow(0.10,2)+pow(0.12,2)));
    hHT_muo  ->SetBinContent(7,  2.69); hHT_muo  ->SetBinError(7,sqrt(pow( 1.55,2)+pow( 0.76,2)+pow(0.05,2)+pow(0.12,2)));
    hHT_muo  ->SetBinContent(8,  2.50); hHT_muo  ->SetBinError(8,sqrt(pow( 1.44,2)+pow( 0.73,2)+pow(0.03,2)+pow(0.16,2)));
    //hHT_muo  ->SetBinContent(9,); hHT_muo  ->SetBinError(9,sqrt(pow( ,2)+pow( ,2)+pow(,2)+pow(,2)));
    hHT_muoMC->SetBinContent(1, 12.55); hHT_muoMC->SetBinError(1, 1.01);
    hHT_muoMC->SetBinContent(2,  1.92); hHT_muoMC->SetBinError(2, 0.46);
    hHT_muoMC->SetBinContent(3, 18.47); hHT_muoMC->SetBinError(3, 1.24);
    hHT_muoMC->SetBinContent(4,  6.71); hHT_muoMC->SetBinError(4, 1.30);
    hHT_muoMC->SetBinContent(5,  2.15); hHT_muoMC->SetBinError(5, 0.52);
    hHT_muoMC->SetBinContent(6,  2.42); hHT_muoMC->SetBinError(6, 0.48);
    hHT_muoMC->SetBinContent(7,  3.87); hHT_muoMC->SetBinError(7, 0.76);
    hHT_muoMC->SetBinContent(8,  3.23); hHT_muoMC->SetBinError(8, 0.71);
    hHT_muoMC->SetBinContent(9,  1.30); hHT_muoMC->SetBinError(9, 0.37);

    hHT_tau  ->SetBinContent(1, 10.97); hHT_tau  ->SetBinError(1,sqrt(pow( 9.17,2)+pow( 2.61,2)+pow(0.00,2)+pow(0.00,2)));
    hHT_tau  ->SetBinContent(2,  7.68); hHT_tau  ->SetBinError(2,sqrt(pow( 8.58,2)+pow( 4.78,2)+pow(0.13,2)+pow(0.04,2)));
    hHT_tau  ->SetBinContent(3, 22.64); hHT_tau  ->SetBinError(3,sqrt(pow( 8.42,2)+pow( 3.53,2)+pow(0.31,2)+pow(0.11,2)));
    hHT_tau  ->SetBinContent(4,  3.29); hHT_tau  ->SetBinError(4,sqrt(pow( 4.84,2)+pow( 0.89,2)+pow(0.02,2)+pow(0.00,2)));
  //  hHT_tau  ->SetBinContent(5,); hHT_tau  ->SetBinError(5,sqrt(pow( ,2)+pow( ,2)+pow(,2)+pow(,2)));
    hHT_tau  ->SetBinContent(6,  7.85); hHT_tau  ->SetBinError(6,sqrt(pow( 3.54,2)+pow( 2.16,2)+pow(0.11,2)+pow(0.11,2)));
 //   hHT_tau  ->SetBinContent(7,); hHT_tau  ->SetBinError(7,sqrt(pow( ,2)+pow( ,2)+pow(,2)+pow(,2)));
    hHT_tau  ->SetBinContent(8,  6.12); hHT_tau  ->SetBinError(8,sqrt(pow(7.77,2)+pow( 2.38,2)+pow(0.14,2)+pow(0.98,2)));
 //   hHT_tau  ->SetBinContent(9,); hHT_tau  ->SetBinError(9,sqrt(pow( ,2)+pow( ,2)+pow(,2)+pow(,2)));
    hHT_tauMC->SetBinContent(1, 12.48); hHT_tauMC->SetBinError(1, 0.99);
    hHT_tauMC->SetBinContent(2,  2.04); hHT_tauMC->SetBinError(2, 0.49);
    hHT_tauMC->SetBinContent(3, 23.54); hHT_tauMC->SetBinError(3, 1.49);
    hHT_tauMC->SetBinContent(4,  9.09); hHT_tauMC->SetBinError(4, 1.08);
    hHT_tauMC->SetBinContent(5,  3.03); hHT_tauMC->SetBinError(5, 0.57);
    hHT_tauMC->SetBinContent(6,  3.45); hHT_tauMC->SetBinError(6, 0.61);
    hHT_tauMC->SetBinContent(7,  5.93); hHT_tauMC->SetBinError(7, 0.77);
    hHT_tauMC->SetBinContent(8,  4.80); hHT_tauMC->SetBinError(8, 0.67);
    hHT_tauMC->SetBinContent(9,  2.09); hHT_tauMC->SetBinError(9, 0.49);

    //hard-coded results in different format
    j2b0  ->SetBinContent(1,lHT_ele  ->GetBinContent(1)); j2b0  ->SetBinError(1,lHT_ele  ->GetBinError(1));
    j2b0  ->SetBinContent(2,lHT_muo  ->GetBinContent(1)); j2b0  ->SetBinError(2,lHT_muo  ->GetBinError(1));
    j2b0  ->SetBinContent(3,lHT_tau  ->GetBinContent(1)); j2b0  ->SetBinError(3,lHT_tau  ->GetBinError(1));
    j2b0  ->SetBinContent(4,mHT_ele  ->GetBinContent(1)); j2b0  ->SetBinError(4,mHT_ele  ->GetBinError(1));
    j2b0  ->SetBinContent(5,mHT_muo  ->GetBinContent(1)); j2b0  ->SetBinError(5,mHT_muo  ->GetBinError(1));
    j2b0  ->SetBinContent(6,mHT_tau  ->GetBinContent(1)); j2b0  ->SetBinError(6,mHT_tau  ->GetBinError(1));
    j2b0  ->SetBinContent(7,hHT_ele  ->GetBinContent(1)); j2b0  ->SetBinError(7,hHT_ele  ->GetBinError(1));
    j2b0  ->SetBinContent(8,hHT_muo  ->GetBinContent(1)); j2b0  ->SetBinError(8,hHT_muo  ->GetBinError(1));
    j2b0  ->SetBinContent(9,hHT_tau  ->GetBinContent(1)); j2b0  ->SetBinError(9,hHT_tau  ->GetBinError(1));
    j2b1  ->SetBinContent(1,lHT_ele  ->GetBinContent(2)); j2b1  ->SetBinError(1,lHT_ele  ->GetBinError(2));
    j2b1  ->SetBinContent(2,lHT_muo  ->GetBinContent(2)); j2b1  ->SetBinError(2,lHT_muo  ->GetBinError(2));
    j2b1  ->SetBinContent(3,lHT_tau  ->GetBinContent(2)); j2b1  ->SetBinError(3,lHT_tau  ->GetBinError(2));
    j2b1  ->SetBinContent(4,mHT_ele  ->GetBinContent(2)); j2b1  ->SetBinError(4,mHT_ele  ->GetBinError(2));
    j2b1  ->SetBinContent(5,mHT_muo  ->GetBinContent(2)); j2b1  ->SetBinError(5,mHT_muo  ->GetBinError(2));
    j2b1  ->SetBinContent(6,mHT_tau  ->GetBinContent(2)); j2b1  ->SetBinError(6,mHT_tau  ->GetBinError(2));
    j2b1  ->SetBinContent(7,hHT_ele  ->GetBinContent(2)); j2b1  ->SetBinError(7,hHT_ele  ->GetBinError(2));
    j2b1  ->SetBinContent(8,hHT_muo  ->GetBinContent(2)); j2b1  ->SetBinError(8,hHT_muo  ->GetBinError(2));
    j2b1  ->SetBinContent(9,hHT_tau  ->GetBinContent(2)); j2b1  ->SetBinError(9,hHT_tau  ->GetBinError(2));
    j3b0  ->SetBinContent(1,lHT_ele  ->GetBinContent(3)); j3b0  ->SetBinError(1,lHT_ele  ->GetBinError(3));
    j3b0  ->SetBinContent(2,lHT_muo  ->GetBinContent(3)); j3b0  ->SetBinError(2,lHT_muo  ->GetBinError(3));
    j3b0  ->SetBinContent(3,lHT_tau  ->GetBinContent(3)); j3b0  ->SetBinError(3,lHT_tau  ->GetBinError(3));
    j3b0  ->SetBinContent(4,mHT_ele  ->GetBinContent(3)); j3b0  ->SetBinError(4,mHT_ele  ->GetBinError(3));
    j3b0  ->SetBinContent(5,mHT_muo  ->GetBinContent(3)); j3b0  ->SetBinError(5,mHT_muo  ->GetBinError(3));
    j3b0  ->SetBinContent(6,mHT_tau  ->GetBinContent(3)); j3b0  ->SetBinError(6,mHT_tau  ->GetBinError(3));
    j3b0  ->SetBinContent(7,hHT_ele  ->GetBinContent(3)); j3b0  ->SetBinError(7,hHT_ele  ->GetBinError(3));
    j3b0  ->SetBinContent(8,hHT_muo  ->GetBinContent(3)); j3b0  ->SetBinError(8,hHT_muo  ->GetBinError(3));
    j3b0  ->SetBinContent(9,hHT_tau  ->GetBinContent(3)); j3b0  ->SetBinError(9,hHT_tau  ->GetBinError(3));
    j3b1  ->SetBinContent(1,lHT_ele  ->GetBinContent(4)); j3b1  ->SetBinError(1,lHT_ele  ->GetBinError(4));
    j3b1  ->SetBinContent(2,lHT_muo  ->GetBinContent(4)); j3b1  ->SetBinError(2,lHT_muo  ->GetBinError(4));
    j3b1  ->SetBinContent(3,lHT_tau  ->GetBinContent(4)); j3b1  ->SetBinError(3,lHT_tau  ->GetBinError(4));
    j3b1  ->SetBinContent(4,mHT_ele  ->GetBinContent(4)); j3b1  ->SetBinError(4,mHT_ele  ->GetBinError(4));
    j3b1  ->SetBinContent(5,mHT_muo  ->GetBinContent(4)); j3b1  ->SetBinError(5,mHT_muo  ->GetBinError(4));
    j3b1  ->SetBinContent(6,mHT_tau  ->GetBinContent(4)); j3b1  ->SetBinError(6,mHT_tau  ->GetBinError(4));
    j3b1  ->SetBinContent(7,hHT_ele  ->GetBinContent(4)); j3b1  ->SetBinError(7,hHT_ele  ->GetBinError(4));
    j3b1  ->SetBinContent(8,hHT_muo  ->GetBinContent(4)); j3b1  ->SetBinError(8,hHT_muo  ->GetBinError(4));
    j3b1  ->SetBinContent(9,hHT_tau  ->GetBinContent(4)); j3b1  ->SetBinError(9,hHT_tau  ->GetBinError(4));
    j3b2  ->SetBinContent(1,lHT_ele  ->GetBinContent(5)); j3b2  ->SetBinError(1,lHT_ele  ->GetBinError(5));
    j3b2  ->SetBinContent(2,lHT_muo  ->GetBinContent(5)); j3b2  ->SetBinError(2,lHT_muo  ->GetBinError(5));
    j3b2  ->SetBinContent(3,lHT_tau  ->GetBinContent(5)); j3b2  ->SetBinError(3,lHT_tau  ->GetBinError(5));
    j3b2  ->SetBinContent(4,mHT_ele  ->GetBinContent(5)); j3b2  ->SetBinError(4,mHT_ele  ->GetBinError(5));
    j3b2  ->SetBinContent(5,mHT_muo  ->GetBinContent(5)); j3b2  ->SetBinError(5,mHT_muo  ->GetBinError(5));
    j3b2  ->SetBinContent(6,mHT_tau  ->GetBinContent(5)); j3b2  ->SetBinError(6,mHT_tau  ->GetBinError(5));
    j3b2  ->SetBinContent(7,hHT_ele  ->GetBinContent(5)); j3b2  ->SetBinError(7,hHT_ele  ->GetBinError(5));
    j3b2  ->SetBinContent(8,hHT_muo  ->GetBinContent(5)); j3b2  ->SetBinError(8,hHT_muo  ->GetBinError(5));
    j3b2  ->SetBinContent(9,hHT_tau  ->GetBinContent(5)); j3b2  ->SetBinError(9,hHT_tau  ->GetBinError(5));
    j6b0  ->SetBinContent(1,lHT_ele  ->GetBinContent(6)); j6b0  ->SetBinError(1,lHT_ele  ->GetBinError(6));
    j6b0  ->SetBinContent(2,lHT_muo  ->GetBinContent(6)); j6b0  ->SetBinError(2,lHT_muo  ->GetBinError(6));
    j6b0  ->SetBinContent(3,lHT_tau  ->GetBinContent(6)); j6b0  ->SetBinError(3,lHT_tau  ->GetBinError(6));
    j6b0  ->SetBinContent(4,mHT_ele  ->GetBinContent(6)); j6b0  ->SetBinError(4,mHT_ele  ->GetBinError(6));
    j6b0  ->SetBinContent(5,mHT_muo  ->GetBinContent(6)); j6b0  ->SetBinError(5,mHT_muo  ->GetBinError(6));
    j6b0  ->SetBinContent(6,mHT_tau  ->GetBinContent(6)); j6b0  ->SetBinError(6,mHT_tau  ->GetBinError(6));
    j6b0  ->SetBinContent(7,hHT_ele  ->GetBinContent(6)); j6b0  ->SetBinError(7,hHT_ele  ->GetBinError(6));
    j6b0  ->SetBinContent(8,hHT_muo  ->GetBinContent(6)); j6b0  ->SetBinError(8,hHT_muo  ->GetBinError(6));
    j6b0  ->SetBinContent(9,hHT_tau  ->GetBinContent(6)); j6b0  ->SetBinError(9,hHT_tau  ->GetBinError(6));
    j6b1  ->SetBinContent(1,lHT_ele  ->GetBinContent(7)); j6b1  ->SetBinError(1,lHT_ele  ->GetBinError(7));
    j6b1  ->SetBinContent(2,lHT_muo  ->GetBinContent(7)); j6b1  ->SetBinError(2,lHT_muo  ->GetBinError(7));
    j6b1  ->SetBinContent(3,lHT_tau  ->GetBinContent(7)); j6b1  ->SetBinError(3,lHT_tau  ->GetBinError(7));
    j6b1  ->SetBinContent(4,mHT_ele  ->GetBinContent(7)); j6b1  ->SetBinError(4,mHT_ele  ->GetBinError(7));
    j6b1  ->SetBinContent(5,mHT_muo  ->GetBinContent(7)); j6b1  ->SetBinError(5,mHT_muo  ->GetBinError(7));
    j6b1  ->SetBinContent(6,mHT_tau  ->GetBinContent(7)); j6b1  ->SetBinError(6,mHT_tau  ->GetBinError(7));
    j6b1  ->SetBinContent(7,hHT_ele  ->GetBinContent(7)); j6b1  ->SetBinError(7,hHT_ele  ->GetBinError(7));
    j6b1  ->SetBinContent(8,hHT_muo  ->GetBinContent(7)); j6b1  ->SetBinError(8,hHT_muo  ->GetBinError(7));
    j6b1  ->SetBinContent(9,hHT_tau  ->GetBinContent(7)); j6b1  ->SetBinError(9,hHT_tau  ->GetBinError(7));
    j6b2  ->SetBinContent(1,lHT_ele  ->GetBinContent(8)); j6b2  ->SetBinError(1,lHT_ele  ->GetBinError(8));
    j6b2  ->SetBinContent(2,lHT_muo  ->GetBinContent(8)); j6b2  ->SetBinError(2,lHT_muo  ->GetBinError(8));
    j6b2  ->SetBinContent(3,lHT_tau  ->GetBinContent(8)); j6b2  ->SetBinError(3,lHT_tau  ->GetBinError(8));
    j6b2  ->SetBinContent(4,mHT_ele  ->GetBinContent(8)); j6b2  ->SetBinError(4,mHT_ele  ->GetBinError(8));
    j6b2  ->SetBinContent(5,mHT_muo  ->GetBinContent(8)); j6b2  ->SetBinError(5,mHT_muo  ->GetBinError(8));
    j6b2  ->SetBinContent(6,mHT_tau  ->GetBinContent(8)); j6b2  ->SetBinError(6,mHT_tau  ->GetBinError(8));
    j6b2  ->SetBinContent(7,hHT_ele  ->GetBinContent(8)); j6b2  ->SetBinError(7,hHT_ele  ->GetBinError(8));
    j6b2  ->SetBinContent(8,hHT_muo  ->GetBinContent(8)); j6b2  ->SetBinError(8,hHT_muo  ->GetBinError(8));
    j6b2  ->SetBinContent(9,hHT_tau  ->GetBinContent(8)); j6b2  ->SetBinError(9,hHT_tau  ->GetBinError(8));
    j3b3  ->SetBinContent(1,lHT_ele  ->GetBinContent(9)); j3b3  ->SetBinError(1,lHT_ele  ->GetBinError(9));
    j3b3  ->SetBinContent(2,lHT_muo  ->GetBinContent(9)); j3b3  ->SetBinError(2,lHT_muo  ->GetBinError(9));
    j3b3  ->SetBinContent(3,lHT_tau  ->GetBinContent(9)); j3b3  ->SetBinError(3,lHT_tau  ->GetBinError(9));
    j3b3  ->SetBinContent(4,mHT_ele  ->GetBinContent(9)); j3b3  ->SetBinError(4,mHT_ele  ->GetBinError(9));
    j3b3  ->SetBinContent(5,mHT_muo  ->GetBinContent(9)); j3b3  ->SetBinError(5,mHT_muo  ->GetBinError(9));
    j3b3  ->SetBinContent(6,mHT_tau  ->GetBinContent(9)); j3b3  ->SetBinError(6,mHT_tau  ->GetBinError(9));
    j3b3  ->SetBinContent(7,hHT_ele  ->GetBinContent(9)); j3b3  ->SetBinError(7,hHT_ele  ->GetBinError(9));
    j3b3  ->SetBinContent(8,hHT_muo  ->GetBinContent(9)); j3b3  ->SetBinError(8,hHT_muo  ->GetBinError(9));
    j3b3  ->SetBinContent(9,hHT_tau  ->GetBinContent(9)); j3b3  ->SetBinError(9,hHT_tau  ->GetBinError(9));
    
    j2b0MC->SetBinContent(1,lHT_eleMC->GetBinContent(1)); j2b0MC->SetBinError(1,lHT_eleMC->GetBinError(1));
    j2b0MC->SetBinContent(2,lHT_muoMC->GetBinContent(1)); j2b0MC->SetBinError(2,lHT_muoMC->GetBinError(1));
    j2b0MC->SetBinContent(3,lHT_tauMC->GetBinContent(1)); j2b0MC->SetBinError(3,lHT_tauMC->GetBinError(1));
    j2b0MC->SetBinContent(4,mHT_eleMC->GetBinContent(1)); j2b0MC->SetBinError(4,mHT_eleMC->GetBinError(1));
    j2b0MC->SetBinContent(5,mHT_muoMC->GetBinContent(1)); j2b0MC->SetBinError(5,mHT_muoMC->GetBinError(1));
    j2b0MC->SetBinContent(6,mHT_tauMC->GetBinContent(1)); j2b0MC->SetBinError(6,mHT_tauMC->GetBinError(1));
    j2b0MC->SetBinContent(7,hHT_eleMC->GetBinContent(1)); j2b0MC->SetBinError(7,hHT_eleMC->GetBinError(1));
    j2b0MC->SetBinContent(8,hHT_muoMC->GetBinContent(1)); j2b0MC->SetBinError(8,hHT_muoMC->GetBinError(1));
    j2b0MC->SetBinContent(9,hHT_tauMC->GetBinContent(1)); j2b0MC->SetBinError(9,hHT_tauMC->GetBinError(1));
    j2b1MC->SetBinContent(1,lHT_eleMC->GetBinContent(2)); j2b1MC->SetBinError(1,lHT_eleMC->GetBinError(2));
    j2b1MC->SetBinContent(2,lHT_muoMC->GetBinContent(2)); j2b1MC->SetBinError(2,lHT_muoMC->GetBinError(2));
    j2b1MC->SetBinContent(3,lHT_tauMC->GetBinContent(2)); j2b1MC->SetBinError(3,lHT_tauMC->GetBinError(2));
    j2b1MC->SetBinContent(4,mHT_eleMC->GetBinContent(2)); j2b1MC->SetBinError(4,mHT_eleMC->GetBinError(2));
    j2b1MC->SetBinContent(5,mHT_muoMC->GetBinContent(2)); j2b1MC->SetBinError(5,mHT_muoMC->GetBinError(2));
    j2b1MC->SetBinContent(6,mHT_tauMC->GetBinContent(2)); j2b1MC->SetBinError(6,mHT_tauMC->GetBinError(2));
    j2b1MC->SetBinContent(7,hHT_eleMC->GetBinContent(2)); j2b1MC->SetBinError(7,hHT_eleMC->GetBinError(2));
    j2b1MC->SetBinContent(8,hHT_muoMC->GetBinContent(2)); j2b1MC->SetBinError(8,hHT_muoMC->GetBinError(2));
    j2b1MC->SetBinContent(9,hHT_tauMC->GetBinContent(2)); j2b1MC->SetBinError(9,hHT_tauMC->GetBinError(2));
    j3b0MC->SetBinContent(1,lHT_eleMC->GetBinContent(3)); j3b0MC->SetBinError(1,lHT_eleMC->GetBinError(3));
    j3b0MC->SetBinContent(2,lHT_muoMC->GetBinContent(3)); j3b0MC->SetBinError(2,lHT_muoMC->GetBinError(3));
    j3b0MC->SetBinContent(3,lHT_tauMC->GetBinContent(3)); j3b0MC->SetBinError(3,lHT_tauMC->GetBinError(3));
    j3b0MC->SetBinContent(4,mHT_eleMC->GetBinContent(3)); j3b0MC->SetBinError(4,mHT_eleMC->GetBinError(3));
    j3b0MC->SetBinContent(5,mHT_muoMC->GetBinContent(3)); j3b0MC->SetBinError(5,mHT_muoMC->GetBinError(3));
    j3b0MC->SetBinContent(6,mHT_tauMC->GetBinContent(3)); j3b0MC->SetBinError(6,mHT_tauMC->GetBinError(3));
    j3b0MC->SetBinContent(7,hHT_eleMC->GetBinContent(3)); j3b0MC->SetBinError(7,hHT_eleMC->GetBinError(3));
    j3b0MC->SetBinContent(8,hHT_muoMC->GetBinContent(3)); j3b0MC->SetBinError(8,hHT_muoMC->GetBinError(3));
    j3b0MC->SetBinContent(9,hHT_tauMC->GetBinContent(3)); j3b0MC->SetBinError(9,hHT_tauMC->GetBinError(3));
    j3b1MC->SetBinContent(1,lHT_eleMC->GetBinContent(4)); j3b1MC->SetBinError(1,lHT_eleMC->GetBinError(4));
    j3b1MC->SetBinContent(2,lHT_muoMC->GetBinContent(4)); j3b1MC->SetBinError(2,lHT_muoMC->GetBinError(4));
    j3b1MC->SetBinContent(3,lHT_tauMC->GetBinContent(4)); j3b1MC->SetBinError(3,lHT_tauMC->GetBinError(4));
    j3b1MC->SetBinContent(4,mHT_eleMC->GetBinContent(4)); j3b1MC->SetBinError(4,mHT_eleMC->GetBinError(4));
    j3b1MC->SetBinContent(5,mHT_muoMC->GetBinContent(4)); j3b1MC->SetBinError(5,mHT_muoMC->GetBinError(4));
    j3b1MC->SetBinContent(6,mHT_tauMC->GetBinContent(4)); j3b1MC->SetBinError(6,mHT_tauMC->GetBinError(4));
    j3b1MC->SetBinContent(7,hHT_eleMC->GetBinContent(4)); j3b1MC->SetBinError(7,hHT_eleMC->GetBinError(4));
    j3b1MC->SetBinContent(8,hHT_muoMC->GetBinContent(4)); j3b1MC->SetBinError(8,hHT_muoMC->GetBinError(4));
    j3b1MC->SetBinContent(9,hHT_tauMC->GetBinContent(4)); j3b1MC->SetBinError(9,hHT_tauMC->GetBinError(4));
    j3b2MC->SetBinContent(1,lHT_eleMC->GetBinContent(5)); j3b2MC->SetBinError(1,lHT_eleMC->GetBinError(5));
    j3b2MC->SetBinContent(2,lHT_muoMC->GetBinContent(5)); j3b2MC->SetBinError(2,lHT_muoMC->GetBinError(5));
    j3b2MC->SetBinContent(3,lHT_tauMC->GetBinContent(5)); j3b2MC->SetBinError(3,lHT_tauMC->GetBinError(5));
    j3b2MC->SetBinContent(4,mHT_eleMC->GetBinContent(5)); j3b2MC->SetBinError(4,mHT_eleMC->GetBinError(5));
    j3b2MC->SetBinContent(5,mHT_muoMC->GetBinContent(5)); j3b2MC->SetBinError(5,mHT_muoMC->GetBinError(5));
    j3b2MC->SetBinContent(6,mHT_tauMC->GetBinContent(5)); j3b2MC->SetBinError(6,mHT_tauMC->GetBinError(5));
    j3b2MC->SetBinContent(7,hHT_eleMC->GetBinContent(5)); j3b2MC->SetBinError(7,hHT_eleMC->GetBinError(5));
    j3b2MC->SetBinContent(8,hHT_muoMC->GetBinContent(5)); j3b2MC->SetBinError(8,hHT_muoMC->GetBinError(5));
    j3b2MC->SetBinContent(9,hHT_tauMC->GetBinContent(5)); j3b2MC->SetBinError(9,hHT_tauMC->GetBinError(5));
    j6b0MC->SetBinContent(1,lHT_eleMC->GetBinContent(6)); j6b0MC->SetBinError(1,lHT_eleMC->GetBinError(6));
    j6b0MC->SetBinContent(2,lHT_muoMC->GetBinContent(6)); j6b0MC->SetBinError(2,lHT_muoMC->GetBinError(6));
    j6b0MC->SetBinContent(3,lHT_tauMC->GetBinContent(6)); j6b0MC->SetBinError(3,lHT_tauMC->GetBinError(6));
    j6b0MC->SetBinContent(4,mHT_eleMC->GetBinContent(6)); j6b0MC->SetBinError(4,mHT_eleMC->GetBinError(6));
    j6b0MC->SetBinContent(5,mHT_muoMC->GetBinContent(6)); j6b0MC->SetBinError(5,mHT_muoMC->GetBinError(6));
    j6b0MC->SetBinContent(6,mHT_tauMC->GetBinContent(6)); j6b0MC->SetBinError(6,mHT_tauMC->GetBinError(6));
    j6b0MC->SetBinContent(7,hHT_eleMC->GetBinContent(6)); j6b0MC->SetBinError(7,hHT_eleMC->GetBinError(6));
    j6b0MC->SetBinContent(8,hHT_muoMC->GetBinContent(6)); j6b0MC->SetBinError(8,hHT_muoMC->GetBinError(6));
    j6b0MC->SetBinContent(9,hHT_tauMC->GetBinContent(6)); j6b0MC->SetBinError(9,hHT_tauMC->GetBinError(6));
    j6b1MC->SetBinContent(1,lHT_eleMC->GetBinContent(7)); j6b1MC->SetBinError(1,lHT_eleMC->GetBinError(7));
    j6b1MC->SetBinContent(2,lHT_muoMC->GetBinContent(7)); j6b1MC->SetBinError(2,lHT_muoMC->GetBinError(7));
    j6b1MC->SetBinContent(3,lHT_tauMC->GetBinContent(7)); j6b1MC->SetBinError(3,lHT_tauMC->GetBinError(7));
    j6b1MC->SetBinContent(4,mHT_eleMC->GetBinContent(7)); j6b1MC->SetBinError(4,mHT_eleMC->GetBinError(7));
    j6b1MC->SetBinContent(5,mHT_muoMC->GetBinContent(7)); j6b1MC->SetBinError(5,mHT_muoMC->GetBinError(7));
    j6b1MC->SetBinContent(6,mHT_tauMC->GetBinContent(7)); j6b1MC->SetBinError(6,mHT_tauMC->GetBinError(7));
    j6b1MC->SetBinContent(7,hHT_eleMC->GetBinContent(7)); j6b1MC->SetBinError(7,hHT_eleMC->GetBinError(7));
    j6b1MC->SetBinContent(8,hHT_muoMC->GetBinContent(7)); j6b1MC->SetBinError(8,hHT_muoMC->GetBinError(7));
    j6b1MC->SetBinContent(9,hHT_tauMC->GetBinContent(7)); j6b1MC->SetBinError(9,hHT_tauMC->GetBinError(7));
    j6b2MC->SetBinContent(1,lHT_eleMC->GetBinContent(8)); j6b2MC->SetBinError(1,lHT_eleMC->GetBinError(8));
    j6b2MC->SetBinContent(2,lHT_muoMC->GetBinContent(8)); j6b2MC->SetBinError(2,lHT_muoMC->GetBinError(8));
    j6b2MC->SetBinContent(3,lHT_tauMC->GetBinContent(8)); j6b2MC->SetBinError(3,lHT_tauMC->GetBinError(8));
    j6b2MC->SetBinContent(4,mHT_eleMC->GetBinContent(8)); j6b2MC->SetBinError(4,mHT_eleMC->GetBinError(8));
    j6b2MC->SetBinContent(5,mHT_muoMC->GetBinContent(8)); j6b2MC->SetBinError(5,mHT_muoMC->GetBinError(8));
    j6b2MC->SetBinContent(6,mHT_tauMC->GetBinContent(8)); j6b2MC->SetBinError(6,mHT_tauMC->GetBinError(8));
    j6b2MC->SetBinContent(7,hHT_eleMC->GetBinContent(8)); j6b2MC->SetBinError(7,hHT_eleMC->GetBinError(8));
    j6b2MC->SetBinContent(8,hHT_muoMC->GetBinContent(8)); j6b2MC->SetBinError(8,hHT_muoMC->GetBinError(8));
    j6b2MC->SetBinContent(9,hHT_tauMC->GetBinContent(8)); j6b2MC->SetBinError(9,hHT_tauMC->GetBinError(8));
    j3b3MC->SetBinContent(1,lHT_eleMC->GetBinContent(9)); j3b3MC->SetBinError(1,lHT_eleMC->GetBinError(9));
    j3b3MC->SetBinContent(2,lHT_muoMC->GetBinContent(9)); j3b3MC->SetBinError(2,lHT_muoMC->GetBinError(9));
    j3b3MC->SetBinContent(3,lHT_tauMC->GetBinContent(9)); j3b3MC->SetBinError(3,lHT_tauMC->GetBinError(9));
    j3b3MC->SetBinContent(4,mHT_eleMC->GetBinContent(9)); j3b3MC->SetBinError(4,mHT_eleMC->GetBinError(9));
    j3b3MC->SetBinContent(5,mHT_muoMC->GetBinContent(9)); j3b3MC->SetBinError(5,mHT_muoMC->GetBinError(9));
    j3b3MC->SetBinContent(6,mHT_tauMC->GetBinContent(9)); j3b3MC->SetBinError(6,mHT_tauMC->GetBinError(9));
    j3b3MC->SetBinContent(7,hHT_eleMC->GetBinContent(9)); j3b3MC->SetBinError(7,hHT_eleMC->GetBinError(9));
    j3b3MC->SetBinContent(8,hHT_muoMC->GetBinContent(9)); j3b3MC->SetBinError(8,hHT_muoMC->GetBinError(9));
    j3b3MC->SetBinContent(9,hHT_tauMC->GetBinContent(9)); j3b3MC->SetBinError(9,hHT_tauMC->GetBinError(9));

	//store the histograms - note that this is also used later for final result tables and plots
	TFile *file = new TFile("../Results/Filtered/LostLepton_Visualization.root","RECREATE");
	file->cd();
	lHT_ele->Write();
	lHT_muo->Write();
	lHT_tau->Write();
	mHT_ele->Write();
	mHT_muo->Write();
	mHT_tau->Write();
	hHT_ele->Write();
	hHT_muo->Write();
	hHT_tau->Write();
	lHT_eleMC->Write();
	lHT_muoMC->Write();
	lHT_tauMC->Write();
	mHT_eleMC->Write();
	mHT_muoMC->Write();
	mHT_tauMC->Write();
	hHT_eleMC->Write();
	hHT_muoMC->Write();
	hHT_tauMC->Write();
	j2b0->Write();
	j2b1->Write();
	j3b0->Write();
	j3b1->Write();
	j3b2->Write();
	j6b0->Write();
	j6b1->Write();
	j6b2->Write();
	j3b3->Write();
	j2b0MC->Write();
	j2b1MC->Write();
	j3b0MC->Write();
	j3b1MC->Write();
	j3b2MC->Write();
	j6b0MC->Write();
	j6b1MC->Write();
	j6b2MC->Write();
	j3b3MC->Write();
	haxis->Write();
	haxis2->Write();
	file->Close();
	cout << "histograms saved in " << file->GetName() << endl;

   TLatex *   tex = new TLatex(0.216443,0.95,"CMS Preliminary, #sqrt{s} = 8 TeV, L = 19.5 fb^{-1}");
   tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.04181185);
   tex->SetLineWidth(2);

    TLatex TitleBox;
    TitleBox.SetNDC();
    TitleBox.SetTextAlign(12);
    TitleBox.SetTextFont(42);
    TitleBox.SetTextSize(0.04181185);
    TitleBox.SetLineWidth(2);
	TString text;
    string outname;
    double max = 0.;
    double max1,max2;

   TCanvas *c1 = new TCanvas("c1", "Canvas_1",70,22,600,600);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
    c1->Range(-1.421903,-81.49007,9.824057,596.1642);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.18);
   c1->SetRightMargin(0.05);
   c1->SetTopMargin(0.07);
   c1->SetBottomMargin(0.15);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);

    c1->Clear();
    c1->cd();
    max1=lHT_eleMC->GetMaximum()+lHT_eleMC->GetBinError(lHT_eleMC->GetMaximumBin());
    max2=lHT_ele  ->GetMaximum()+lHT_ele  ->GetBinError(lHT_ele  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis2->SetMaximum(max);
    text = "lost e, low H_{T}";
    haxis2->Draw("");
    lHT_eleMC->Draw("sameE2");
    lHT_ele->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = lHT_ele->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=lHT_muoMC->GetMaximum()+lHT_muoMC->GetBinError(lHT_muoMC->GetMaximumBin());
    max2=lHT_muo  ->GetMaximum()+lHT_muo  ->GetBinError(lHT_muo  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis2->SetMaximum(max);
    text = "lost #mu, low H_{T}";
    haxis2->Draw("");
    lHT_muoMC->Draw("sameE2");
    lHT_muo->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.864583,text.Data());
    outname = lHT_muo->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=lHT_tauMC->GetMaximum()+lHT_tauMC->GetBinError(lHT_tauMC->GetMaximumBin());
    max2=lHT_tau  ->GetMaximum()+lHT_tau  ->GetBinError(lHT_tau  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis2->SetMaximum(max);
    text = "lost #tau, low H_{T}";
    haxis2->Draw("");
    lHT_tauMC->Draw("sameE2");
    lHT_tau->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = lHT_tau->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    
    c1->Clear();
    c1->cd();
    max1=mHT_eleMC->GetMaximum()+mHT_eleMC->GetBinError(mHT_eleMC->GetMaximumBin());
    max2=mHT_ele  ->GetMaximum()+mHT_ele  ->GetBinError(mHT_ele  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis2->SetMaximum(max);
    text = "lost e, medium H_{T}";
    haxis2->Draw("");
    mHT_eleMC->Draw("sameE2");
    mHT_ele->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = mHT_ele->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    getchar();
    c1->Clear();
    c1->cd();
    max1=mHT_muoMC->GetMaximum()+mHT_muoMC->GetBinError(mHT_muoMC->GetMaximumBin());
    max2=mHT_muo  ->GetMaximum()+mHT_muo  ->GetBinError(mHT_muo  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis2->SetMaximum(max);
    text = "lost #mu, medium H_{T}";
    haxis2->Draw("");
    mHT_muoMC->Draw("sameE2");
    mHT_muo->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = mHT_muo->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=mHT_tauMC->GetMaximum()+mHT_tauMC->GetBinError(mHT_tauMC->GetMaximumBin());
    max2=mHT_tau  ->GetMaximum()+mHT_tau  ->GetBinError(mHT_tau  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis2->SetMaximum(max);
    text = "lost #tau, medium H_{T}";
    haxis2->Draw("");
    mHT_tauMC->Draw("sameE2");
    mHT_tau->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = mHT_tau->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    
    c1->Clear();
    c1->cd();
    max1=hHT_eleMC->GetMaximum()+hHT_eleMC->GetBinError(hHT_eleMC->GetMaximumBin());
    max2=hHT_ele  ->GetMaximum()+hHT_ele  ->GetBinError(hHT_ele  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis2->SetMaximum(max);
    text = "lost e, high H_{T}";
    haxis2->Draw("");
    hHT_eleMC->Draw("sameE2");
    hHT_ele->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = hHT_ele->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=hHT_muoMC->GetMaximum()+hHT_muoMC->GetBinError(hHT_muoMC->GetMaximumBin());
    max2=hHT_muo  ->GetMaximum()+hHT_muo  ->GetBinError(hHT_muo  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis2->SetMaximum(max);
    text = "lost #mu, high H_{T}";
    haxis2->Draw("");
    hHT_muoMC->Draw("sameE2");
    hHT_muo->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = hHT_muo->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=hHT_tauMC->GetMaximum()+hHT_tauMC->GetBinError(hHT_tauMC->GetMaximumBin());
    max2=hHT_tau  ->GetMaximum()+hHT_tau  ->GetBinError(hHT_tau  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis2->SetMaximum(max);
    text = "lost #tau, high H_{T}";
    haxis2->Draw("");
    hHT_tauMC->Draw("sameE2");
    hHT_tau->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = hHT_tau->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    c1->cd();
    gPad->SetLogy(1);
    
    
    
    c1->Clear();
    c1->cd();
    max1=lHT_eleMC->GetMaximum()+lHT_eleMC->GetBinError(lHT_eleMC->GetMaximumBin());
    max2=lHT_ele  ->GetMaximum()+lHT_ele  ->GetBinError(lHT_ele  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis2->SetMaximum(max);
    haxis2->SetMinimum(1.);
    text = "lost e, low H_{T}";
    haxis2->Draw("");
    lHT_eleMC->Draw("sameE2");
    lHT_ele->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = lHT_ele->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=lHT_muoMC->GetMaximum()+lHT_muoMC->GetBinError(lHT_muoMC->GetMaximumBin());
    max2=lHT_muo  ->GetMaximum()+lHT_muo  ->GetBinError(lHT_muo  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis2->SetMaximum(max);
    haxis2->SetMinimum(1.);
    text = "lost #mu, low H_{T}";
    haxis2->Draw("");
    lHT_muoMC->Draw("sameE2");
    lHT_muo->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = lHT_muo->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=lHT_tauMC->GetMaximum()+lHT_tauMC->GetBinError(lHT_tauMC->GetMaximumBin());
    max2=lHT_tau  ->GetMaximum()+lHT_tau  ->GetBinError(lHT_tau  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis2->SetMaximum(max);
    haxis2->SetMinimum(1.);
    text = "lost #tau, low H_{T}";
    haxis2->Draw("");
    lHT_tauMC->Draw("sameE2");
    lHT_tau->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = lHT_tau->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
    
    
    c1->Clear();
    c1->cd();
    max1=mHT_eleMC->GetMaximum()+mHT_eleMC->GetBinError(mHT_eleMC->GetMaximumBin());
    max2=mHT_ele  ->GetMaximum()+mHT_ele  ->GetBinError(mHT_ele  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis2->SetMaximum(max);
    haxis2->SetMinimum(1.);
    text = "lost e, medium H_{T}";
    haxis2->Draw("");
    mHT_eleMC->Draw("sameE2");
    mHT_ele->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = mHT_ele->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=mHT_muoMC->GetMaximum()+mHT_muoMC->GetBinError(mHT_muoMC->GetMaximumBin());
    max2=mHT_muo  ->GetMaximum()+mHT_muo  ->GetBinError(mHT_muo  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis2->SetMaximum(max);
    haxis2->SetMinimum(1.);
    text = "lost #mu, medium H_{T}";
    haxis2->Draw("");
    mHT_muoMC->Draw("sameE2");
    mHT_muo->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = mHT_muo->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=mHT_tauMC->GetMaximum()+mHT_tauMC->GetBinError(mHT_tauMC->GetMaximumBin());
    max2=mHT_tau  ->GetMaximum()+mHT_tau  ->GetBinError(mHT_tau  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis2->SetMaximum(max);
    haxis2->SetMinimum(1.);
    text = "lost #tau, medium H_{T}";
    haxis2->Draw("");
    mHT_tauMC->Draw("sameE2");
    mHT_tau->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = mHT_tau->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
    
    
    c1->Clear();
    c1->cd();
    max1=hHT_eleMC->GetMaximum()+hHT_eleMC->GetBinError(hHT_eleMC->GetMaximumBin());
    max2=hHT_ele  ->GetMaximum()+hHT_ele  ->GetBinError(hHT_ele  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis2->SetMaximum(max);
    haxis2->SetMinimum(1.);
    text = "lost e, high H_{T}";
    haxis2->Draw("");
    hHT_eleMC->Draw("sameE2");
    hHT_ele->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = hHT_ele->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=hHT_muoMC->GetMaximum()+hHT_muoMC->GetBinError(hHT_muoMC->GetMaximumBin());
    max2=hHT_muo  ->GetMaximum()+hHT_muo  ->GetBinError(hHT_muo  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis2->SetMaximum(max);
    haxis2->SetMinimum(1.);
    text = "lost #mu, high H_{T}";
    haxis2->Draw("");
    hHT_muoMC->Draw("sameE2");
    hHT_muo->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = hHT_muo->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=hHT_tauMC->GetMaximum()+hHT_tauMC->GetBinError(hHT_tauMC->GetMaximumBin());
    max2=hHT_tau  ->GetMaximum()+hHT_tau  ->GetBinError(hHT_tau  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis2->SetMaximum(max);
    haxis2->SetMinimum(1.);
    text = "lost #tau, high H_{T}";
    haxis2->Draw("");
    hHT_tauMC->Draw("sameE2");
    hHT_tau->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = hHT_tau->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
  
    c1->cd();
    gPad->SetLogy(0);
    
    c1->Clear();
    c1->cd();
    max1=j2b0MC->GetMaximum()+j2b0MC->GetBinError(j2b0MC->GetMaximumBin());
    max2=j2b0  ->GetMaximum()+j2b0  ->GetBinError(j2b0  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis->SetMaximum(max);
    text = "2 jets, 0 b jets";
    haxis->Draw("");
    j2b0MC->Draw("sameE2");
    j2b0->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j2b0->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=j2b1MC->GetMaximum()+j2b1MC->GetBinError(j2b1MC->GetMaximumBin());
    max2=j2b1  ->GetMaximum()+j2b1  ->GetBinError(j2b1  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis->SetMaximum(max);
    text = "2 jets, #geq1 b jet";
    haxis->Draw("");
    j2b1MC->Draw("sameE2");
    j2b1->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j2b1->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=j3b0MC->GetMaximum()+j3b0MC->GetBinError(j3b0MC->GetMaximumBin());
    max2=j3b0  ->GetMaximum()+j3b0  ->GetBinError(j3b0  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis->SetMaximum(max);
    text = "3-5 jets, 0 b jets";
    haxis->Draw("");
    j3b0MC->Draw("sameE2");
    j3b0->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j3b0->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=j3b1MC->GetMaximum()+j3b1MC->GetBinError(j3b1MC->GetMaximumBin());
    max2=j3b1  ->GetMaximum()+j3b1  ->GetBinError(j3b1  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis->SetMaximum(max);
    text = "3-5 jets, 1 b jet";
    haxis->Draw("");
    j3b1MC->Draw("sameE2");
    j3b1->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j3b1->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=j3b2MC->GetMaximum()+j3b2MC->GetBinError(j3b2MC->GetMaximumBin());
    max2=j3b2  ->GetMaximum()+j3b2  ->GetBinError(j3b2  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis->SetMaximum(max);
    text = "3-5 jets, 2 b jets";
    haxis->Draw("");
    j3b2MC->Draw("sameE2");
    j3b2->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j3b2->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=j6b0MC->GetMaximum()+j6b0MC->GetBinError(j6b0MC->GetMaximumBin());
    max2=j6b0  ->GetMaximum()+j6b0  ->GetBinError(j6b0  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis->SetMaximum(max);
    text = "#geq6 jets, 0 b jets";
    haxis->Draw("");
    j6b0MC->Draw("sameE2");
    j6b0->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j6b0->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=j6b1MC->GetMaximum()+j6b1MC->GetBinError(j6b1MC->GetMaximumBin());
    max2=j6b1  ->GetMaximum()+j6b1  ->GetBinError(j6b1  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis->SetMaximum(max);
    text = "#geq6 jets, 1 b jet";
    haxis->Draw("");
    j6b1MC->Draw("sameE2");
    j6b1->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j6b1->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=j6b2MC->GetMaximum()+j6b2MC->GetBinError(j6b2MC->GetMaximumBin());
    max2=j6b2  ->GetMaximum()+j6b2  ->GetBinError(j6b2  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis->SetMaximum(max);
    text = "#geq6 jets, 2 b jets";
    haxis->Draw("");
    j6b2MC->Draw("sameE2");
    j6b2->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j6b2->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=j3b3MC->GetMaximum()+j3b3MC->GetBinError(j3b3MC->GetMaximumBin());
    max2=j3b3  ->GetMaximum()+j3b3  ->GetBinError(j3b3  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 1.25*max;
    haxis->SetMaximum(max);
    text = "#geq3 jets, #geq3 b jets";
    haxis->Draw("");
    j3b3MC->Draw("sameE2");
    j3b3->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j3b3->GetName();outname = "../Results/Filtered/LostLepton/"+outname + ".eps";
    c1->SaveAs(outname.c_str());
    
    c1->cd();
    gPad->SetLogy(1);
    
    
    
    c1->Clear();
    c1->cd();
    max1=j2b0MC->GetMaximum()+j2b0MC->GetBinError(j2b0MC->GetMaximumBin());
    max2=j2b0  ->GetMaximum()+j2b0  ->GetBinError(j2b0  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis->SetMaximum(max);
    text = "2 jets, 0 b jets";
    haxis->Draw("");
    j2b0MC->Draw("sameE2");
    j2b0->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j2b0->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=j2b1MC->GetMaximum()+j2b1MC->GetBinError(j2b1MC->GetMaximumBin());
    max2=j2b1  ->GetMaximum()+j2b1  ->GetBinError(j2b1  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis->SetMaximum(max);
    text = "2 jets, #geq1 b jet";
    haxis->Draw("");
    j2b1MC->Draw("sameE2");
    j2b1->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j2b1->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=j3b0MC->GetMaximum()+j3b0MC->GetBinError(j3b0MC->GetMaximumBin());
    max2=j3b0  ->GetMaximum()+j3b0  ->GetBinError(j3b0  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis->SetMaximum(max);
    text = "3-5 jets, 0 b jets";
    haxis->Draw("");
    j3b0MC->Draw("sameE2");
    j3b0->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j3b0->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=j3b1MC->GetMaximum()+j3b1MC->GetBinError(j3b1MC->GetMaximumBin());
    max2=j3b1  ->GetMaximum()+j3b1  ->GetBinError(j3b1  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis->SetMaximum(max);
    text = "3-5 jets, 1 b jet";
    haxis->Draw("");
    j3b1MC->Draw("sameE2");
    j3b1->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j3b1->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=j3b2MC->GetMaximum()+j3b2MC->GetBinError(j3b2MC->GetMaximumBin());
    max2=j3b2  ->GetMaximum()+j3b2  ->GetBinError(j3b2  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis->SetMaximum(max);
    text = "3-5 jets, 2 b jets";
    haxis->Draw("");
    j3b2MC->Draw("sameE2");
    j3b2->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j3b2->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=j6b0MC->GetMaximum()+j6b0MC->GetBinError(j6b0MC->GetMaximumBin());
    max2=j6b0  ->GetMaximum()+j6b0  ->GetBinError(j6b0  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis->SetMaximum(max);
    text = "#geq6 jets, 0 b jets";
    haxis->Draw("");
    j6b0MC->Draw("sameE2");
    j6b0->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j6b0->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=j6b1MC->GetMaximum()+j6b1MC->GetBinError(j6b1MC->GetMaximumBin());
    max2=j6b1  ->GetMaximum()+j6b1  ->GetBinError(j6b1  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis->SetMaximum(max);
    text = "#geq 6 jets, 1 b jet";
    haxis->Draw("");
    j6b1MC->Draw("sameE2");
    j6b1->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j6b1->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=j6b2MC->GetMaximum()+j6b2MC->GetBinError(j6b2MC->GetMaximumBin());
    max2=j6b2  ->GetMaximum()+j6b2  ->GetBinError(j6b2  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis->SetMaximum(max);
    text = "#geq 6 jets, 2 b jets";
    haxis->Draw("");
    j6b2MC->Draw("sameE2");
    j6b2->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j6b2->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());
    
    c1->Clear();
    c1->cd();
    max1=j3b3MC->GetMaximum()+j3b3MC->GetBinError(j3b3MC->GetMaximumBin());
    max2=j3b3  ->GetMaximum()+j3b3  ->GetBinError(j3b3  ->GetMaximumBin());
    max  = (max1>max2)?max1:max2;
    max = 5.0*max;
    haxis->SetMaximum(max);
    text = "#geq 3 jets, #geq 3 b jets";
    haxis->Draw("");
    j3b3MC->Draw("sameE2");
    j3b3->Draw("sameE1");
    tex->Draw();
    leg->Draw();
    TitleBox.DrawLatex(0.25,0.844406,text.Data());
    outname = j3b3->GetName();outname = "../Results/Filtered/LostLepton/"+outname + "_log.eps";
    c1->SaveAs(outname.c_str());

}