#include "TEventList.h"
#include "TLorentzVector.h"
#include "TMath.h"
#include "TString.h"
#include "TObject.h"
#include "TFile.h"
#include "TDirectory.h"
#include "TTree.h"
#include "TCut.h"
#include "TROOT.h"
#include "TSystem.h"
#include <iostream>
#include <sstream>
#include <fstream>
#include <iomanip>
#include <math.h>
#include <vector>
#include <stdlib.h>
#include <stdio.h>
#include <string>
#include <cmath>
#include <limits.h>
#include <utility>
#include "/shome/haweber/MT2Analysis_8TeV/Code/MT2AnalysisCode/MT2Code/include/MT2tree.hh"//use your own path of MT2tree.cc

//run via root -l -b -q RemoveEventsMT2tree.C

using namespace std;

//comment below shows what code does, we decided not to use this macro, but rather add tagger as additional branch
void RemoveEventsMT2tree() {
// Example of Root macro to copy a subset of a Tree to a new Tree
// Only selected entries are copied to the new Tree.
// The input file has been generated by the program in $ROOTSYS/test/Event
// with   Event 1000 1 99 1
//Author: Rene Brun
   
//modified: Hannsjoerg Weber, 28/08/2013

   //make cleaning
   // get eventlist to clean
   vector<pair<int,pair<int,int> > > rls; rls.clear();
   ifstream filterdat("/shome/haweber/AODFiles_MT2SR/txtfiles/controlregion/filterRA2b/JetHT_Run2012B-13Jul2012-v1_AOD_2.txt");
   char buffer[200];
   while( filterdat.getline(buffer, 200, '\n') ){
	int rrun(-1), lls(-1), eevent(-1), d1(-1);
//	sscanf(buffer, "*\t%d\t*\t%d\t*\t%d\t*\t%d", &d1, &rrun, &lls, &eevent);
	sscanf(buffer, "%d:%d:%d",&rrun, &lls, &eevent);
	cout << rrun<<":"<<lls<<":"<<eevent << endl;
	if(eevent<0||eevent>INT_MAX) cout << rrun<<":"<<lls<<":"<<eevent << " - be careful for this event number" << endl;
	pair<int,int> t1(lls,eevent);
	pair<int,pair<int,int> > t2(rrun,t1);
	rls.push_back(t2);
   }

   // get the old rootfile including fake events and define new events
   TString oldfilename = "bla.root";
   TString newfilename = "bla_cleaned3.root";

	// if you want to apply an additional event selection, define cuts here
	std::ostringstream cutStream;
	std::ostringstream cutStreamBase;
	cutStream << " " 
		<< "NTausIDLoose3Hits==0"                   << "&&"
		<< "NMuons==0"                              << "&&"
		<< "NEles==0"                               << "&&"
		<< "misc.Jet0Pass ==1"                      << "&&"
		<< "misc.Jet1Pass ==1"                      << "&&"
		<< "misc.Vectorsumpt < 70";
		cutStream  << "&& misc.MinMetJetDPhi4Pt40 >0.3";
		cutStream << "&&((misc.MET>200&&misc.HT<=750&&misc.HT>=450&&misc.MT2>200)||(misc.HT>750&&misc.MET>30&&misc.MT2>=100))";
//	         cutStream << "&&misc.MT2>=100";//lowest border in MT2
	
	cutStreamBase << " " 
      << "misc.PassJet40ID ==1"                      << "&&"
      << "(misc.HBHENoiseFlag == 0 || misc.ProcessID==10)"  << "&&" // for rare SM samples
      << "misc.CSCTightHaloIDFlag == 0"             << "&&"
      << "misc.trackingFailureFlag==0"              << "&&"
      << "misc.eeBadScFlag==0"                      << "&&"
      << "misc.EcalDeadCellTriggerPrimitiveFlag==0" << "&&"
      << "misc.TrackingManyStripClusFlag==0"             << "&&"
      << "misc.TrackingTooManyStripClusFlag==0"          << "&&"
      << "misc.TrackingLogErrorTooManyClustersFlag==0"   << "&&"
      << "misc.CrazyHCAL==0";

	TString cuts = cutStream.str().c_str();
	TString basecuts = cutStreamBase.str().c_str();
//	TString myCuts = cuts + "&&" + basecuts;
	TString myCuts = "";// if no cuts should be selected DO NOT comment this line

   //Get old file, old tree and set top branch address
   TFile *oldfile = new TFile(oldfilename.Data());
   TTree *oldtree = (TTree*)oldfile->Get("MassTree");

   MT2tree* fMT2tree = new MT2tree();
   oldtree->SetBranchAddress("MT2tree", &fMT2tree);
   Long64_t nentries =  oldtree->GetEntries();
   Long64_t nbytes = 0, nb = 0;
   int nev =0;

   //Create a new file + a clone of old tree in new file
   TFile *newfile = new TFile(newfilename.Data(),"RECREATE");
   TTree *newtree = oldtree->CloneTree(0);

   oldtree->Draw(">>selList", myCuts);
   TEventList *myEvtList = (TEventList*)gDirectory->Get("selList");
   oldtree->SetEventList(myEvtList);
   int counter=0;
   int numEvt = myEvtList->GetN();
   int printEvt = 100000;
   if(myEvtList->GetN()<1000000) printEvt = myEvtList->GetN()/25;
   cout << "Filtering done, size=" <<myEvtList->GetN()  << endl;
//   if(myEvtList->GetSize()==0) continue;
   while(myEvtList->GetEntry(counter++) !=-1){
	int jentry = myEvtList->GetEntry(counter-1);
	nb =  oldtree->GetEntry(jentry);   nbytes += nb;
	oldtree->SetBranchAddress("MT2tree", &fMT2tree);
	if(counter%printEvt==0) cout << "Process event " << counter << endl;	

	//make cleaning
	bool keep = true;
	int p=-1;
	for(int nn=0; nn<rls.size();++nn){
		if(rls[nn].first!=fMT2tree->misc.Run) continue; // --> run over matching 
		if((rls[nn].second).first!=fMT2tree->misc.LumiSection) continue; // --> LS over matching 
		if(fMT2tree->misc.Event>0){
			if((rls[nn].second).second==fMT2tree->misc.Event) { 
				//cout << "Veto event " << fMT2tree->misc.Run<<":"<<fMT2tree->misc.LumiSection<<":"<<fMT2tree->misc.Event << " - events left for vetoing " << rls.size()-1 << endl;
				keep=false; p=nn; break;
			}
		}
		else{
			cout << "check " << "event in tree " << fMT2tree->misc.Event << endl;
			cout << "event to check " << (rls[nn].second).second << endl;
			int evtt = (rls[nn].second).second + INT_MAX;
			evtt = evtt - INT_MAX;
			cout << "and now? " << evtt << endl;
			//has evtt now also wrong negative sign?
			if(evtt==fMT2tree->misc.Event) {keep=false; p=nn; break;}
		}
	}
	if(keep) newtree->Fill();
	else{
		int tt = p;//sint(rls.begin()+p);
		cout << "Erase " << rls[tt].first <<":"<<(rls[tt].second).first << ":" <<(rls[tt].second).second << endl;
		rls.erase(rls.begin()+p);
	}
   }
   newtree->Print();
   newtree->AutoSave();
   delete oldfile;
   delete newfile;
}



